### ISSUE TITLE
支持CH集群吗,大神

### ISSUE THREAD

**Issue by LyStormrage** [RickyHuo/teleport#7]
可以像类似于BalanceClickhouseDataSource这种方式支持多节点吗

**Comment by RickyHuo** [comment]
@LyStormrage  我们线上一般是通过域名实现负载均衡已经方便动态扩容。

Teleport也支持多节点的方式。

```
output:
    - clickhouse:
          table: "msg_null"
          host: "ck31:9000"
          clickhouse.read_timeout: 10
          clickhouse.write_timeout: 20
          clickhouse.debug: "false"
          clickhouse.compress: "true"
          clickhouse.database: "push"
          clickhouse.username: "user"
          clickhouse.password: "passwd"
          clickhouse.alt_hosts: "ck32:9000,ck33.:9000,ck34:9000"
          fields: ["date", "time", "app", "datatype", "token", ...]
          bulk_size: 30000
```
相关驱动链接参考：
https://github.com/kshvakov/clickhouse#dsn
